/**
 * Static data constants
 * Extracted from components to reduce memory usage and improve performance
 */

export const NATUREZAS_JURIDICAS = [
  { label: '101-5 - Órgão Público do Poder Executivo Federal', value: '1015' },
  { label: '102-3 - Órgão Público do Poder Executivo Estadual ou do Distrito Federal', value: '1023' },
  { label: '103-1 - Órgão Público do Poder Executivo Municipal', value: '1031' },
  { label: '104-0 - Órgão Público do Poder Legislativo Federal', value: '1040' },
  { label: '105-8 - Órgão Público do Poder Legislativo Estadual ou do DF', value: '1058' },
  { label: '106-6 - Órgão Público do Poder Legislativo Municipal', value: '1066' },
  { label: '107-4 - Órgão Público do Poder Judiciário Federal', value: '1074' },
  { label: '108-2 - Órgão Público do Poder Judiciário Estadual', value: '1082' },
  { label: '110-4 - Autarquia Federal', value: '1104' },
  { label: '111-2 - Autarquia Estadual ou do Distrito Federal', value: '1112' },
  { label: '112-0 - Autarquia Municipal', value: '1120' },
  { label: '113-9 - Fundação Pública de Direito Público Federal', value: '1139' },
  { label: '114-7 - Fundação Pública de Direito Público Estadual ou do Distrito Federal', value: '1147' },
  { label: '115-5 - Fundação Pública de Direito Público Municipal', value: '1155' },
  { label: '116-3 - Órgão Público Autônomo Federal', value: '1163' },
  { label: '117-1 - Órgão Público Autônomo Estadual ou do Distrito Federal', value: '1171' },
  { label: '118-0 - Órgão Público Autônomo Municipal', value: '1180' },
  { label: '119-8 - Comissão Polinacional', value: '1198' },
  { label: '121-0 - Consórcio Público de Direito Público (Associação Pública)', value: '1210' },
  { label: '122-8 - Consórcio Público de Direito Privado', value: '1228' },
  { label: '123-6 - Estado ou Distrito Federal', value: '1236' },
  { label: '124-4 - Município', value: '1244' },
  { label: '125-2 - Fundação Pública de Direito Privado Federal', value: '1252' },
  { label: '126-0 - Fundação Pública de Direito Privado Estadual ou do Distrito Federal', value: '1260' },
  { label: '127-9 - Fundação Pública de Direito Privado Municipal', value: '1279' },
  { label: '128-7 - Fundo Público da Administração Indireta Federal', value: '1287' },
  { label: '129-5 - Fundo Público da Administração Indireta Estadual ou do Distrito Federa', value: '1295' },
  { label: '130-9 - Fundo Público da Administração Indireta Municipal', value: '1309' },
  { label: '131-7 - Fundo Público da Administração Direta Federal', value: '1317' },
  { label: '132-5 - Fundo Público da Administração Direta Estadual ou do Distrito Federal', value: '1325' },
  { label: '133-3 - Fundo Público da Administração Direta Municipal', value: '1333' },
  { label: '134-1 - União', value: '1341' },
  { label: '201-1 - Empresa Pública', value: '2011' },
  { label: '203-8 - Sociedade de Economia Mista', value: '2038' },
  { label: '204-6 - Sociedade Anônima Aberta', value: '2046' },
  { label: '205-4 - Sociedade Anônima Fechada', value: '2054' },
  { label: '206-2 - Sociedade Empresária Limitada (LTDA)', value: '2062' },
  { label: '207-0 - Sociedade Empresária em Nome Coletivo', value: '2070' },
  { label: '208-9 - Sociedade Empresária em Comandita Simples', value: '2089' },
  { label: '209-7 - Sociedade Empresária em Comandita por Ações', value: '2097' },
  { label: '212-7 - Sociedade em Conta de Participação', value: '2127' },
  { label: '213-5 - Empresário (Individual) (EI)', value: '2135' },
  { label: '214-3 - Cooperativa', value: '2143' },
  { label: '215-1 - Consórcio de Sociedades', value: '2151' },
  { label: '216-0 - Grupo de Sociedades', value: '2160' },
  { label: '217-8 - Estabelecimento, no Brasil, de Sociedade Estrangeira', value: '2178' },
  { label: '219-4 - Estabelecimento, no Brasil, de Empresa Binacional Argentino-Brasileira', value: '2194' },
  { label: '221-6 - Empresa Domiciliada no Exterior', value: '2216' },
  { label: '222-4 - Clube/Fundo de Investimento', value: '2224' },
  { label: '223-2 - Sociedade Simples Pura', value: '2232' },
  { label: '224-0 - Sociedade Simples Limitada', value: '2240' },
  { label: '225-9 - Sociedade Simples em Nome Coletivo', value: '2259' },
  { label: '226-7 - Sociedade Simples em Comandita Simples', value: '2267' },
  { label: '228-3 - Consórcio de Empregadores', value: '2283' },
  { label: '229-1 - Consórcio Simples', value: '2291' },
  { label: '230-5 - Empresa Individual de Responsabilidade Limitada (de Natureza Empresária) (EIRELI)', value: '2305' },
  { label: '231-3 - Empresa Individual de Responsabilidade Limitada (de Natureza Simples) (EIRELI)', value: '2313' },
  { label: '232-1 - Sociedade Unipessoal de Advocacia', value: '2321' },
  { label: '233-0 - Cooperativas de Consumo', value: '2330' },
  { label: '234-8 - Sociedade de Advocacia', value: '2348' },
  { label: '235-6 - Sociedade Unipessoal Imobiliária', value: '2356' },
  { label: '236-4 - Sociedade de Propósito Específico', value: '2364' },
  { label: '303-4 - Serviço Notarial e Registral (Cartório)', value: '3034' },
  { label: '306-9 - Fundação Privada', value: '3069' },
  { label: '307-7 - Serviço Social Autônomo', value: '3077' },
  { label: '308-5 - Condomínio Edilício', value: '3085' },
  { label: '310-7 - Comissão de Conciliação Prévia', value: '3107' },
  { label: '311-5 - Entidade de Mediação e Arbitragem', value: '3115' },
  { label: '312-3 - Partido Político', value: '3123' },
  { label: '313-1 - Entidade Sindical', value: '3131' },
  { label: '320-4 - Estabelecimento, no Brasil, de Fundação ou Associação Estrangeiras', value: '3204' },
  { label: '321-2 - Fundação ou Associação Domiciliada no Exterior', value: '3212' },
  { label: '322-0 - Organização Religiosa', value: '3220' },
  { label: '323-9 - Comunidade Indígena', value: '3239' },
  { label: '324-7 - Fundo Privado', value: '3247' },
  { label: '325-5 - Órgão de Direção Nacional de Partido Político', value: '3255' },
  { label: '326-3 - Órgão de Direção Regional de Partido Político', value: '3263' },
  { label: '327-1 - Órgão de Direção Local de Partido Político', value: '3271' },
  { label: '331-0 - Organização Social (OS)', value: '3310' },
  { label: '399-9 - Associação Privada', value: '3999' },
  { label: '213-5 - Microempreendedor Individual (MEI)', value: '2135' },
  { label: '401-4 - Empresa Individual Imobiliária', value: '4014' },
  { label: '402-2 - Segurado Especial', value: '4022' },
  { label: '408-1 - Contribuinte individual', value: '4081' },
  { label: '409-0 - Candidato a Cargo Político Eletivo', value: '4090' },
  { label: '411-1 - Leiloeiro', value: '4111' },
  { label: '412-0 - Produtor Rural (Pessoa Física)', value: '4120' },
] as const;

export const PORTES = [
  { label: 'MEI - Microempreendedor Individual', value: '00' },
  { label: 'ME - Microempresa', value: '02' },
  { label: 'EPP - Empresa de Pequeno Porte', value: '03' },
  { label: 'Demais', value: '05' },
] as const;

export const RAMOS_ATIVIDADE = [
  { label: 'Tecnologia da Informação', value: 'TI' },
  { label: 'Educação', value: 'EDUCACAO' },
  { label: 'Saúde', value: 'SAUDE' },
  { label: 'Comércio', value: 'COMERCIO' },
  { label: 'Indústria', value: 'INDUSTRIA' },
  { label: 'Serviços', value: 'SERVICOS' },
  { label: 'Construção Civil', value: 'CONSTRUCAO' },
  { label: 'Agronegócio', value: 'AGRONEGOCIO' },
  { label: 'Transporte e Logística', value: 'TRANSPORTE' },
  { label: 'Alimentação', value: 'ALIMENTACAO' }
] as const;

export const ESTADOS = [
  { label: 'Acre', value: 'AC', id: 1 },
  { label: 'Alagoas', value: 'AL', id: 2 },
  { label: 'Amapá', value: 'AP', id: 3 },
  { label: 'Amazonas', value: 'AM', id: 4 },
  { label: 'Bahia', value: 'BA', id: 5 },
  { label: 'Ceará', value: 'CE', id: 6 },
  { label: 'Distrito Federal', value: 'DF', id: 7 },
  { label: 'Espírito Santo', value: 'ES', id: 8 },
  { label: 'Goiás', value: 'GO', id: 9 },
  { label: 'Maranhão', value: 'MA', id: 10 },
  { label: 'Mato Grosso', value: 'MT', id: 11 },
  { label: 'Mato Grosso do Sul', value: 'MS', id: 12 },
  { label: 'Minas Gerais', value: 'MG', id: 13 },
  { label: 'Pará', value: 'PA', id: 14 },
  { label: 'Paraíba', value: 'PB', id: 15 },
  { label: 'Paraná', value: 'PR', id: 16 },
  { label: 'Pernambuco', value: 'PE', id: 17 },
  { label: 'Piauí', value: 'PI', id: 18 },
  { label: 'Rio de Janeiro', value: 'RJ', id: 19 },
  { label: 'Rio Grande do Norte', value: 'RN', id: 20 },
  { label: 'Rio Grande do Sul', value: 'RS', id: 21 },
  { label: 'Rondônia', value: 'RO', id: 22 },
  { label: 'Roraima', value: 'RR', id: 23 },
  { label: 'Santa Catarina', value: 'SC', id: 24 },
  { label: 'São Paulo', value: 'SP', id: 25 },
  { label: 'Sergipe', value: 'SE', id: 26 },
  { label: 'Tocantins', value: 'TO', id: 27 }
] as const;
